
sudo: false
language: node_js: lts
cache:
  directories:
    - node_modules
branches:
  only:
    - main
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run semantic-release